name: Simple

on:
  push:
    

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    
    - run: mkdir -p path/artifact
    - run: cd path/artifact
    - name: dh
      run: dotnet new maui  
    
    - uses: actions/upload-artifact@v4
      with:
       name: my-artifact
       path: path/artifact
