name: Simple

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Maui sdk
      run: dotnet workload install maui --ignore-failed-sources
    - name: new proj
      run: dotnet new maui -n "Simple"
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      
